// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWQEdOyoi5Mn4m1atMBc7NicF7Wn13sos',
    appId: '1:420565243152:web:7f0fac4d8e81582db5c195',
    messagingSenderId: '420565243152',
    projectId: 'todo-meeps-app',
    authDomain: 'todo-meeps-app.firebaseapp.com',
    storageBucket: 'todo-meeps-app.firebasestorage.app',
    measurementId: 'G-Q987910DH8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5zGD2_wpnESp4evsmX7ER68tF69RZgVw',
    appId: '1:420565243152:android:ad7ac899f4752008b5c195',
    messagingSenderId: '420565243152',
    projectId: 'todo-meeps-app',
    storageBucket: 'todo-meeps-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA7zl3DMvlY0uOvFGfRkBM-JPgK6K91qk',
    appId: '1:420565243152:ios:61d8e41d06df11c1b5c195',
    messagingSenderId: '420565243152',
    projectId: 'todo-meeps-app',
    storageBucket: 'todo-meeps-app.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA7zl3DMvlY0uOvFGfRkBM-JPgK6K91qk',
    appId: '1:420565243152:ios:61d8e41d06df11c1b5c195',
    messagingSenderId: '420565243152',
    projectId: 'todo-meeps-app',
    storageBucket: 'todo-meeps-app.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWQEdOyoi5Mn4m1atMBc7NicF7Wn13sos',
    appId: '1:420565243152:web:1762a906895ca229b5c195',
    messagingSenderId: '420565243152',
    projectId: 'todo-meeps-app',
    authDomain: 'todo-meeps-app.firebaseapp.com',
    storageBucket: 'todo-meeps-app.firebasestorage.app',
    measurementId: 'G-1PW85DFNGK',
  );

}